'use client';
import {createContext,useContext,useState,useEffect,useRef} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {X,Plus,Minus,ShoppingBag,ArrowRight,CheckCircle2} from 'lucide-react';
import Link from 'next/link';
import {Product,money} from '@/lib/catalog';
type CartLine={id:string;quantity:number};
type CartContextValue={items:CartLine[];add:(id:string)=>void;openCart:()=>void};
const CartContext=createContext<CartContextValue|null>(null);
export function useCart(){const v=useContext(CartContext);if(!v)throw new Error('Cart provider is missing');return v;}
export function CartProvider({children,catalog,demo}:{children:React.ReactNode;catalog:Product[];demo:boolean}){
 const [items,setItems]=useState<CartLine[]>([]);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [preview,setPreview]=useState(false);const [ready,setReady]=useState(false);const key=useRef('');
 useEffect(()=>{try{const value=JSON.parse(localStorage.getItem('hes-cart-v1')||'[]');if(Array.isArray(value))setItems(value.filter(x=>catalog.some(p=>p.id===x.id&&p.available)&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=10).slice(0,3));}catch{}setReady(true)},[catalog]);
 useEffect(()=>{if(ready)try{localStorage.setItem('hes-cart-v1',JSON.stringify(items));}catch{}key.current='';setPreview(false);},[items,ready]);
 const add=(id:string)=>{if(!catalog.some(p=>p.id===id&&p.available))return;setItems(old=>old.some(i=>i.id===id)?old.map(i=>i.id===id?{...i,quantity:Math.min(i.quantity+1,10)}:i):[...old,{id,quantity:1}]);setNotice('');setOpen(true)};
 const change=(id:string,delta:number)=>setItems(old=>old.map(i=>i.id===id?{...i,quantity:Math.min(10,i.quantity+delta)}:i).filter(i=>i.quantity>0));
 const total=items.reduce((sum,i)=>sum+(catalog.find(p=>p.id===i.id)?.amount||0)*i.quantity,0);
 const checkout=async()=>{setBusy(true);setNotice('');try{key.current ||= crypto.randomUUID();const res=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key.current},body:JSON.stringify({items})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Checkout is unavailable. Please try again.');if(data.demo){setPreview(true);}else if(typeof data.url==='string'&&new URL(data.url).hostname==='checkout.stripe.com'){window.location.assign(data.url)}else throw new Error('Unable to open secure checkout.');}catch(e){setNotice(e instanceof Error?e.message:'Something went wrong.');}finally{setBusy(false)}};
 return <CartContext.Provider value={{items,add,openCart:()=>{setNotice('');setOpen(true)}}}>{children}<Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="cart-drawer"><div className="drawer-heading"><div><span className="eyebrow">A LITTLE SUPPORT GOES A LONG WAY</span><Dialog.Title>Your bag</Dialog.Title></div><Dialog.Close className="icon-button" aria-label="Close bag"><X/></Dialog.Close></div><Dialog.Description className="drawer-description">{demo?'Preview bag · Example prices. No payment will be taken.':'Review your items before secure checkout.'}</Dialog.Description>{items.length===0?<div className="empty-cart"><ShoppingBag size={48}/><h3>A fresh start is waiting.</h3><p>Explore tools and coaching for your everyday health.</p><Dialog.Close asChild><Link href="/shop" className="button button-primary">Explore the shop <ArrowRight/></Link></Dialog.Close></div>:<><ul className="cart-lines">{items.map(i=>{const p=catalog.find(p=>p.id===i.id)!;return <li key={i.id}><div className={'mini-product '+p.id}><ShoppingBag/></div><div className="cart-line-copy"><h3>{p.name}</h3><p>{money(p.amount)}</p><div className="quantity"><button className="icon-button" onClick={()=>change(i.id,-1)} aria-label={'Remove one '+p.name}><Minus size={16}/></button><span aria-label="Quantity">{i.quantity}</span><button className="icon-button" onClick={()=>change(i.id,1)} disabled={i.quantity===10} aria-label={'Add one '+p.name}><Plus size={16}/></button></div></div><button className="text-button" onClick={()=>setItems(old=>old.filter(x=>x.id!==i.id))} aria-label={'Remove '+p.name}>Remove</button></li>})}</ul><div className="cart-total"><span>Subtotal</span><strong>{money(total)}</strong></div><p className="small-copy">{demo?'Illustrative USD pricing. Final products and prices are set before launch.':'Shipping and any applicable taxes are shown at checkout.'}</p>{preview&&<div className="notice success" role="status"><CheckCircle2/><div><strong>Your preview is ready.</strong><p>This is a demonstration. No order was placed and no payment was taken.</p></div></div>}{notice&&<p className="notice error" role="alert">{notice}</p>}<button className="button button-primary full-width" onClick={checkout} disabled={busy}>{busy?'Preparing checkout…':demo?'Preview checkout':'Continue to secure checkout'}<ArrowRight size={21}/></button></>}</Dialog.Content></Dialog.Portal></Dialog.Root></CartContext.Provider>
}


