import 'server-only';
import {createHash} from 'node:crypto';import {ZodError} from 'zod';import {isLive,siteUrl} from './config';import {assertSameOrigin,validIdempotencyKey} from './validation';import {database} from './db';
export class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
export async function readJson(request:Request){if(!request.headers.get('content-type')?.startsWith('application/json'))throw new ApiError(415,'Send JSON content.');const declared=Number(request.headers.get('content-length')||0);if(declared>10000)throw new ApiError(413,'Request is too large.');const text=await request.text();if(text.length>10000)throw new ApiError(413,'Request is too large.');try{return JSON.parse(text)}catch{throw new ApiError(400,'Invalid request.')}}
export function guardOrigin(request:Request){try{assertSameOrigin(request.headers.get('origin'),siteUrl());}catch{throw new ApiError(403,'This request is not allowed.')}}
export function requestKey(request:Request){const key=request.headers.get('idempotency-key');if(!validIdempotencyKey(key))throw new ApiError(400,'Refresh the page and try again.');return key!;}
export async function rateLimit(request:Request,scope:string,limit=15){if(!isLive())return;if(!process.env.RATE_LIMIT_SALT)throw new ApiError(503,'This service is not ready yet.');const ip=process.env.VERCEL?request.headers.get('x-vercel-forwarded-for')?.split(',')[0]||'shared':request.headers.get('x-forwarded-for')?.split(',')[0]||'shared';const key=createHash('sha256').update(process.env.RATE_LIMIT_SALT+scope+ip).digest('hex');const window=Math.floor(Date.now()/600000);const sql=database();const result=await sql`INSERT INTO request_limits (key, window_id, hits) VALUES (${key},${window},1) ON CONFLICT (key) DO UPDATE SET hits=CASE WHEN request_limits.window_id=EXCLUDED.window_id THEN request_limits.hits+1 ELSE 1 END,window_id=EXCLUDED.window_id RETURNING hits`;if(Number(result[0].hits)>limit)throw new ApiError(429,'Please wait a few minutes before trying again.');}
export function apiFailure(error:unknown){if(error instanceof ZodError)return Response.json({error:'Please check your details and try again.'},{status:400});if(error instanceof ApiError)return Response.json({error:error.message},{status:error.status});console.error('HES service error:',error instanceof Error?error.name:'UnknownError');return Response.json({error:'This service is temporarily unavailable. Please try again later.'},{status:503});}

